def main():
    # Augmented Assigment Operator
    score = 10
    score += 10
    print(score)

    # Substraction Assignment Operator
    #x -= y
    score = 100
    score -= 15
    print(score)

    # Multiplication Assignment Operator
    balance = 10
    balance *= 4
    print(balance)

    # Division Assignment Operator
    x = 10
    x /= 5
    print(x)

    # Modulus Assigment Operator

    a = 10
    b = 4

    a %= b
    print(a)



if __name__ == "__main__":
    main()
